### PR TITLE
run integration tests against schema-simplification

### PR DESCRIPTION
**Pull request by mwes**

### CODE REVIEW

**Comment by mwes** [comment]
This is up to calling xplan:
```
export XPLAN_PATH=/xplan/code
cd /xplan/xplan_api
python3 example/yeast_gates_doe_biofab.py -e 10545 -g nor -m 4
Generating Plan for Gate: UWBF_NOR ...  Create a problem instance? [Y/n] Traceback (most recent call last):
  File "example/yeast_gates_doe_biofab.py", line 36, in <module>
    media_choice=args.media)
  File "/xplan/xplan_api/example/yeast_gates_doe.py", line 31, in yeast_gates_doe
    run_settings = settings.get_settings(args)
  File "/xplan/xplan_api/xplan_api/settings.py", line 235, in get_settings
    settings = interactive_prompt()
  File "/xplan/xplan_api/xplan_api/settings.py", line 253, in interactive_prompt
    option['default'])
  File "/xplan/xplan_api/xplan_api/settings.py", line 204, in prompt_bool
    res = input('{prompt} {def_string} '.format(**locals()))
EOFError: EOF when reading a line
```

**Comment by mwes** [comment]
@mdehavensift @danbryce This is failing with the below error message now at plan generation on the `schema-simplification` branch.
```+ python3 example/yeast_gates_doe_biofab.py -e 10545 -g nor -m 4 -c example/configs/no_upload.json
Generating Plan for Gate: UWBF_NOR ...  resources['antibiotics']: Do not have data for experiment_set: yeast-gates_q0
resources['treatments']: Do not have data for experiment_set: yeast-gates_q0
Traceback (most recent call last):
  File "example/yeast_gates_doe_biofab.py", line 36, in <module>
    media_choice=args.media)
  File "/xplan/xplan_api/example/yeast_gates_doe.py", line 182, in yeast_gates_doe
    pdf_output_path=os.path.splitext(plan_out)[0] + '.pdf' if run_settings.visualize else None)
  File "/xplan/xplan_api/xplan_api/xplan.py", line 91, in run_xplan
    pdf_output_path=pdf_output_path)
  File "/xplan/xplan_api/xplan_api/xplan.py", line 113, in run_xplan_problem
    cmd=cmd_list, ec=exit_code, so=out, se=err
xplan_api.xplan.XPlanFailed: ['sbcl', '--dynamic-space-size', '4096', '--script', 'run-xplan.lisp', 'models/domains/sd2-domain.lisp', '/tmp/tmpprq1fndl'] failed with exit code 1
b''
b'WARNING:\nCouldn\'t re-execute SBCL with proper personality flags (/proc isn\'t mounted? setuid?)\nTrying to continue anyway.\nUnhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING\n                                                              {1001E06E93}>:\n  Component :ITERATE not found, required by #<SYSTEM "xplan">\n\nBacktrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001E06E93}>\n0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component :ITERATE not found, required by #<SYSTEM "xplan"> #<unavailable argument>)\n1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* Component :ITERATE not found, required by #<SYSTEM "xplan">)\n2: (INVOKE-DEBUGGER Component :ITERATE not found, required by #<SYSTEM "xplan">)\n3: (ERROR ASDF/FIND-COMPONENT:MISSING-DEPENDENCY :REQUIRED-BY #<ASDF/SYSTEM:SYSTEM "xplan"> :REQUIRES :ITERATE)\n4: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "xplan"> :ITERATE NIL)\n5: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "xplan"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BEC2B}>)\n6: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n7: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "xplan"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BEBCB}>) [fast-method]\n8: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan" "package"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BE6CB}>)\n9: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n10: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan" "package"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BE66B}>) [fast-method]\n11: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan" "package"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BDDDB}>)\n12: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n13: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan" "package"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BDD7B}>) [fast-method]\n14: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BDA2B}>)\n15: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n16: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {10041BD9CB}>) [fast-method]\n17: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E270EB}>)\n18: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n19: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E2708B}>) [fast-method]\n20: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan-user" "xpu-package"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E23A8B}>)\n21: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n22: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan-user" "xpu-package"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E23A2B}>) [fast-method]\n23: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan-user" "xpu-package"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E20EDB}>)\n24: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n25: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "xplan-user" "xpu-package"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E20E7B}>) [fast-method]\n26: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E1D73B}>)\n27: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))\n28: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003E16EC3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {1003E1D6DB}>) [fast-method]\n29: ((:METHOD ASDF/PLAN:MAKE-PLAN (T ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) NIL #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user">) [fast-method]\n30: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user">) [fast-method]\n31: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user">)\n32: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))\n33: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "xplan-user">) [fast-method]\n34: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :XPLAN-USER)\n35: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))\n36: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10038D9EAB}> :OVERRIDE NIL :KEY NIL)\n37: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :XPLAN-USER) [fast-method]\n38: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :XPLAN-USER) [fast-method]\n39: (ASDF/OPERATE:LOAD-SYSTEM :XPLAN-USER)\n40: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:LOAD-SYSTEM :XPLAN-USER) #<NULL-LEXENV>)\n41: (EVAL-TLF (ASDF/OPERATE:LOAD-SYSTEM :XPLAN-USER) 5 NIL)\n42: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ASDF/OPERATE:LOAD-SYSTEM :XPLAN-USER) 5)\n43: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (ASDF/OPERATE:LOAD-SYSTEM :XPLAN-USER) :CURRENT-INDEX 5)\n44: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {1001E187DB}> #<SB-C::SOURCE-INFO {1001E18793}> SB-C::INPUT-ERROR-IN-LOAD)\n45: (SB-INT:LOAD-AS-SOURCE #<SB-SYS:FD-STREAM for "file /xplan/code/run-xplan.lisp" {1001E0E5B3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")\n46: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /xplan/code/run-xplan.lisp" {1001E0E5B3}> NIL)\n47: (LOAD #<SB-SYS:FD-STREAM for "file /xplan/code/run-xplan.lisp" {1001E0E5B3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)\n48: ((FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT) #<SB-SYS:FD-STREAM for "file /xplan/code/run-xplan.lisp" {1001E0E5B3}>)\n49: ((FLET #:WITHOUT-INTERRUPTS-BODY-146 :IN SB-IMPL::PROCESS-SCRIPT))\n50: (SB-IMPL::PROCESS-SCRIPT "run-xplan.lisp")\n51: (SB-IMPL::TOPLEVEL-INIT)\n52: ((FLET #:WITHOUT-INTERRUPTS-BODY-77 :IN SAVE-LISP-AND-DIE))\n53: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))\n\nunhandled condition in --disable-debugger mode, quitting\n'
[Pipeline] }```

**Comment by mdehavensift** [comment]
I'll try to figure out what's going wrong with sbcl

**Comment by mdehavensift** [comment]
Can't replicate locally. This tests works for me.
Seems to be an issue that can occur with sbcl running inside docker sometimes. Trying to find a solution.

**Comment by mwvaughn** [comment]
Zynda noted this too since its embedded in the Jupyter image. No known fix but to wrap the usage of sbcl in a try statement

On May 4, 2018, at 2:41 PM, mdehavensift <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't replicate locally. This tests works for me.
Seems to be an issue that can occur with sbcl running inside docker sometimes. Trying to find a solution.

**Comment by mdehavensift** [comment]
Nevermind, this might just be an issue with the external requirements for xplan not being pulled. They were being pulled via a script in xplan_api, but that's not there anymore so the externals weren't being grabbed anywhere.

Pushed a fix. We'll see if it works.

**Comment by mdehavensift** [comment]
Pulling the xplan externals fixed the previous issue. It looks like ta3-api is failing to validate the plan result. Checking into this now.

**Comment by mwes** [comment]
Thanks, yes, the sbcl warning has not caused issues before. Even with the tests passing, the generation invocation was causing what looks like a separate failure.

**Comment by mwes** [comment]
@mdehavensift let me know if you need any help debugging. One of the major changes in the schema was how source URIs are handled. These are now arrays of objects, with attributes that can be applied: Example: 

```
                        "source": [
                            {
                                "sample": "agave://data-sd2e-community/sample/biofab/yeast-gates_q0/3/107795/B12"
                            }
                        ]```

**Comment by mdehavensift** [comment]
@mwes I fixed a couple of small issues on Friday, then ran into that change with the sample URIs. That requires changing the planning domain model. I'm working on that one today. Just from looking through the schema, I don't think there will be too much more to change after the source URIs line up, but it's hard to say for sure until I can get past this error during validation.

**Comment by mdehavensift** [comment]
Yeast gates XPlan output is very nearly passing the schema locally. The changes to match the schema has broken some of the graphing code, so that will need to be fixed before merging. Also have a couple questions for Ben to make sure the output is okay.

**Comment by mdehavensift** [comment]
retest this please

**Comment by mwes** [comment]
```
Traceback (most recent call last):
  File "example/yeast_gates_doe_biofab.py", line 36, in <module>
    media_choice=args.media)
  File "/xplan/xplan_api/example/yeast_gates_doe.py", line 182, in yeast_gates_doe
    pdf_output_path=os.path.splitext(plan_out)[0] + '.pdf' if run_settings.visualize else None)
  File "/xplan/xplan_api/xplan_api/xplan.py", line 91, in run_xplan
    pdf_output_path=pdf_output_path)
  File "/xplan/xplan_api/xplan_api/xplan.py", line 124, in run_xplan_problem
    shutil.copy(os.path.join(self.xplan_path, 'ps.pdf'), pdf_output_path)
  File "/usr/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/xplan/code/ps.pdf
```

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Pull request merged**
